import type { AppDict } from './dict-types'

// TODO: verify translation
const dict: AppDict = {
  common: {
    save: 'ذخیره',
    cancel: 'لغو',
    delete: 'حذف',
    loading: 'در حال بارگذاری…',
    back: 'بازگشت',
    or: 'یا',
    appName: 'Nova',
    error: 'مشکلی پیش آمد',
  },
  nav: {
    home: 'خانه',
    dashboard: 'داشبورد',
    admin: 'مدیریت',
    login: 'ورود',
    signup: 'ثبت‌نام',
    logout: 'خروج',
    profile: 'پروفایل',
  },
  home: {
    badge: 'شروع آمادهٔ تولید',
    title: 'اپلیکیشن‌های چندزبانه را سریع بسازید',
    subtitle:
      'Next.js + Supabase + Vercel با احراز هویت، RLS، پنل ادمین و پنج زبان از روز اول.',
    ctaPrimary: 'ساخت حساب',
    ctaSecondary: 'ورود',
    feature1Title: 'سرورمحور',
    feature1Body: 'Server Components و Server Actions — جاوااسکریپت کمتر در کلاینت.',
    feature2Title: 'امنیت پیش‌فرض',
    feature2Body: 'Supabase Auth + RLS روی همه جداول.',
    feature3Title: 'i18n + RTL',
    feature3Body: 'انگلیسی، ترکی، روسی، فارسی و عبری — با پشتیبانی راست‌به‌چپ.',
  },
  auth: {
    loginTitle: 'خوش آمدید',
    loginSubtitle: 'برای ادامه وارد شوید',
    signupTitle: 'ساخت حساب',
    signupSubtitle: 'کمتر از یک دقیقه',
    email: 'ایمیل',
    password: 'رمز عبور',
    firstName: 'نام',
    lastName: 'نام خانوادگی',
    forgot: 'رمز را فراموش کردید؟',
    noAccount: 'حساب ندارید؟',
    hasAccount: 'قبلاً حساب دارید؟',
    submitLogin: 'ورود',
    submitSignup: 'ساخت حساب',
    signupSuccessTitle: 'ایمیل را بررسی کنید',
    signupSuccessBody: 'لینک تأیید فرستادیم. برای فعال‌سازی حساب آن را باز کنید.',
    forgotTitle: 'بازنشانی رمز',
    forgotSubtitle: 'یک لینک امن برای بازنشانی می‌فرستیم.',
    forgotSubmit: 'ارسال لینک',
    forgotSent: 'اگر ایمیل وجود داشته باشد، لینک در راه است.',
    resetTitle: 'رمز جدید',
    resetSubtitle: 'یک رمز قوی برای حساب خود وارد کنید.',
    resetSubmit: 'به‌روزرسانی رمز',
    newPassword: 'رمز جدید',
    confirmPassword: 'تأیید رمز',
  },
  dashboard: {
    title: 'داشبورد',
    welcome: 'سلام، {name}',
    pending: 'حساب شما در انتظار تأیید است.',
    approved: 'حساب شما تأیید شده و آماده‌اید.',
    rejected: 'حساب شما تأیید نشد. با پشتیبانی تماس بگیرید.',
    noProfile: 'پروفایل هنوز یافت نشد. کمی بعد تازه کنید.',
  },
  admin: {
    title: 'مدیریت',
    subtitle: 'کاربران و تأییدها',
    users: 'کاربران',
    role: 'نقش',
    status: 'وضعیت',
    approve: 'تأیید',
    reject: 'رد',
    forbidden: 'دسترسی مدیر ندارید.',
    empty: 'هنوز کاربری نیست.',
  },
  language: {
    label: 'زبان',
    en: 'English',
    tr: 'Türkçe',
    ru: 'Русский',
    fa: 'فارسی',
    he: 'עברית',
  },
}

export default dict
