import type { AppDict } from './dict-types'

// TODO: verify translation
const dict: AppDict = {
  common: {
    save: 'שמור',
    cancel: 'ביטול',
    delete: 'מחק',
    loading: 'טוען…',
    back: 'חזרה',
    or: 'או',
    appName: 'Nova',
    error: 'משהו השתבש',
  },
  nav: {
    home: 'בית',
    dashboard: 'לוח בקרה',
    admin: 'ניהול',
    login: 'התחברות',
    signup: 'הרשמה',
    logout: 'התנתקות',
    profile: 'פרופיל',
  },
  home: {
    badge: 'סטארטר מוכן לפרודקשן',
    title: 'שגרו אפליקציות רב־לשוניות במהירות',
    subtitle:
      'Next.js + Supabase + Vercel עם אימות, RLS, אדמין וחמש שפות מהיום הראשון.',
    ctaPrimary: 'יצירת חשבון',
    ctaSecondary: 'התחברות',
    feature1Title: 'שרת־ראשון',
    feature1Body: 'Server Components ו־Server Actions — פחות JS בלקוח.',
    feature2Title: 'אבטחה כברירת מחדל',
    feature2Body: 'Supabase Auth + Row Level Security בכל טבלה.',
    feature3Title: 'i18n + RTL',
    feature3Body: 'אנגלית, טורקית, רוסית, פרסית ועברית — כולל RTL.',
  },
  auth: {
    loginTitle: 'ברוכים השבים',
    loginSubtitle: 'התחברו כדי להמשיך',
    signupTitle: 'יצירת חשבון',
    signupSubtitle: 'פחות מדקה',
    email: 'אימייל',
    password: 'סיסמה',
    firstName: 'שם פרטי',
    lastName: 'שם משפחה',
    forgot: 'שכחתם סיסמה?',
    noAccount: 'אין לכם חשבון?',
    hasAccount: 'כבר יש חשבון?',
    submitLogin: 'התחברות',
    submitSignup: 'יצירת חשבון',
    signupSuccessTitle: 'בדקו את האימייל',
    signupSuccessBody: 'שלחנו קישור אישור. פתחו אותו כדי להפעיל את החשבון.',
    forgotTitle: 'איפוס סיסמה',
    forgotSubtitle: 'נשלח קישור מאובטח לאיפוס.',
    forgotSubmit: 'שלח קישור',
    forgotSent: 'אם האימייל קיים, הקישור בדרך.',
    resetTitle: 'בחרו סיסמה חדשה',
    resetSubtitle: 'הזינו סיסמה חזקה לחשבון.',
    resetSubmit: 'עדכן סיסמה',
    newPassword: 'סיסמה חדשה',
    confirmPassword: 'אימות סיסמה',
  },
  dashboard: {
    title: 'לוח בקרה',
    welcome: 'שלום, {name}',
    pending: 'החשבון ממתין לאישור.',
    approved: 'החשבון אושר — אפשר להתחיל.',
    rejected: 'החשבון לא אושר. פנו לתמיכה.',
    noProfile: 'הפרופיל עדיין לא נמצא. רעננו בעוד רגע.',
  },
  admin: {
    title: 'ניהול',
    subtitle: 'משתמשים ואישורים',
    users: 'משתמשים',
    role: 'תפקיד',
    status: 'סטטוס',
    approve: 'אשר',
    reject: 'דחה',
    forbidden: 'אין לך הרשאות מנהל.',
    empty: 'אין משתמשים עדיין.',
  },
  language: {
    label: 'שפה',
    en: 'English',
    tr: 'Türkçe',
    ru: 'Русский',
    fa: 'فارسی',
    he: 'עברית',
  },
}

export default dict
