import type { AppDict } from './dict-types'

// TODO: verify translation
const dict: AppDict = {
  common: {
    save: 'Kaydet',
    cancel: 'İptal',
    delete: 'Sil',
    loading: 'Yükleniyor…',
    back: 'Geri',
    or: 'veya',
    appName: 'Nova',
    error: 'Bir hata oluştu',
  },
  nav: {
    home: 'Ana sayfa',
    dashboard: 'Panel',
    admin: 'Yönetim',
    login: 'Giriş',
    signup: 'Kayıt ol',
    logout: 'Çıkış',
    profile: 'Profil',
  },
  home: {
    badge: 'Üretime hazır başlangıç',
    title: 'Çok dilli uygulamaları hızlı yayınla',
    subtitle:
      'Next.js + Supabase + Vercel: kimlik doğrulama, RLS, yönetim ve ilk günden 5 dil.',
    ctaPrimary: 'Hesap oluştur',
    ctaSecondary: 'Giriş yap',
    feature1Title: 'Sunucu odaklı',
    feature1Body: 'Server Components ve Server Actions — daha az istemci JS.',
    feature2Title: 'Varsayılan güvenlik',
    feature2Body: 'Supabase Auth + her tabloda Row Level Security.',
    feature3Title: 'i18n + RTL',
    feature3Body: 'İngilizce, Türkçe, Rusça, Farsça ve İbranice — RTL dahil.',
  },
  auth: {
    loginTitle: 'Tekrar hoş geldiniz',
    loginSubtitle: 'Devam etmek için giriş yapın',
    signupTitle: 'Hesap oluştur',
    signupSubtitle: 'Bir dakikadan kısa sürer',
    email: 'E-posta',
    password: 'Şifre',
    firstName: 'Ad',
    lastName: 'Soyad',
    forgot: 'Şifremi unuttum?',
    noAccount: 'Hesabınız yok mu?',
    hasAccount: 'Zaten hesabınız var mı?',
    submitLogin: 'Giriş yap',
    submitSignup: 'Hesap oluştur',
    signupSuccessTitle: 'E-postanızı kontrol edin',
    signupSuccessBody: 'Onay bağlantısı gönderdik. Hesabınızı etkinleştirmek için açın.',
    forgotTitle: 'Şifreyi sıfırla',
    forgotSubtitle: 'Güvenli bir sıfırlama bağlantısı göndereceğiz.',
    forgotSubmit: 'Sıfırlama bağlantısı gönder',
    forgotSent: 'E-posta kayıtlıysa bağlantı yoldadır.',
    resetTitle: 'Yeni şifre seçin',
    resetSubtitle: 'Hesabınız için güçlü bir şifre girin.',
    resetSubmit: 'Şifreyi güncelle',
    newPassword: 'Yeni şifre',
    confirmPassword: 'Şifreyi onayla',
  },
  dashboard: {
    title: 'Panel',
    welcome: 'Hoş geldin, {name}',
    pending: 'Hesabınız onay bekliyor.',
    approved: 'Hesabınız onaylandı, hazırsınız.',
    rejected: 'Hesabınız onaylanmadı. Destek ile iletişime geçin.',
    noProfile: 'Profil henüz yok. Biraz sonra yenileyin.',
  },
  admin: {
    title: 'Yönetim',
    subtitle: 'Kullanıcıları ve onayları yönet',
    users: 'Kullanıcılar',
    role: 'Rol',
    status: 'Durum',
    approve: 'Onayla',
    reject: 'Reddet',
    forbidden: 'Yönetici erişiminiz yok.',
    empty: 'Henüz kullanıcı yok.',
  },
  language: {
    label: 'Dil',
    en: 'English',
    tr: 'Türkçe',
    ru: 'Русский',
    fa: 'فارسی',
    he: 'עברית',
  },
}

export default dict
