import type { AppDict } from './dict-types'

// TODO: verify translation
const dict: AppDict = {
  common: {
    save: 'Сохранить',
    cancel: 'Отмена',
    delete: 'Удалить',
    loading: 'Загрузка…',
    back: 'Назад',
    or: 'или',
    appName: 'Nova',
    error: 'Что-то пошло не так',
  },
  nav: {
    home: 'Главная',
    dashboard: 'Кабинет',
    admin: 'Админ',
    login: 'Войти',
    signup: 'Регистрация',
    logout: 'Выйти',
    profile: 'Профиль',
  },
  home: {
    badge: 'Готовый продакшен-стартер',
    title: 'Запускайте мультиязычные приложения быстро',
    subtitle:
      'Next.js + Supabase + Vercel: auth, RLS, админка и 5 языков с первого дня.',
    ctaPrimary: 'Создать аккаунт',
    ctaSecondary: 'Войти',
    feature1Title: 'Сначала сервер',
    feature1Body: 'Server Components и Server Actions — меньше клиентского JS.',
    feature2Title: 'Безопасность по умолчанию',
    feature2Body: 'Supabase Auth + Row Level Security на каждой таблице.',
    feature3Title: 'i18n + RTL',
    feature3Body: 'EN, TR, RU, FA, HE — включая языки справа налево.',
  },
  auth: {
    loginTitle: 'С возвращением',
    loginSubtitle: 'Войдите, чтобы продолжить',
    signupTitle: 'Создать аккаунт',
    signupSubtitle: 'Меньше минуты',
    email: 'Email',
    password: 'Пароль',
    firstName: 'Имя',
    lastName: 'Фамилия',
    forgot: 'Забыли пароль?',
    noAccount: 'Нет аккаунта?',
    hasAccount: 'Уже есть аккаунт?',
    submitLogin: 'Войти',
    submitSignup: 'Создать аккаунт',
    signupSuccessTitle: 'Проверьте почту',
    signupSuccessBody: 'Мы отправили ссылку подтверждения. Откройте её, чтобы активировать аккаунт.',
    forgotTitle: 'Сброс пароля',
    forgotSubtitle: 'Мы отправим безопасную ссылку для сброса.',
    forgotSubmit: 'Отправить ссылку',
    forgotSent: 'Если email существует, ссылка уже в пути.',
    resetTitle: 'Новый пароль',
    resetSubtitle: 'Введите надёжный пароль для аккаунта.',
    resetSubmit: 'Обновить пароль',
    newPassword: 'Новый пароль',
    confirmPassword: 'Подтвердите пароль',
  },
  dashboard: {
    title: 'Кабинет',
    welcome: 'Добро пожаловать, {name}',
    pending: 'Ваш аккаунт ожидает подтверждения.',
    approved: 'Аккаунт подтверждён — можно начинать.',
    rejected: 'Аккаунт не одобрен. Свяжитесь с поддержкой.',
    noProfile: 'Профиль пока не найден. Обновите страницу позже.',
  },
  admin: {
    title: 'Админ',
    subtitle: 'Пользователи и одобрения',
    users: 'Пользователи',
    role: 'Роль',
    status: 'Статус',
    approve: 'Одобрить',
    reject: 'Отклонить',
    forbidden: 'Нет прав администратора.',
    empty: 'Пользователей пока нет.',
  },
  language: {
    label: 'Язык',
    en: 'English',
    tr: 'Türkçe',
    ru: 'Русский',
    fa: 'فارسی',
    he: 'עברית',
  },
}

export default dict
