import type { AppDict } from './dict-types'

const dict: AppDict = {
  common: {
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    loading: 'Loading…',
    back: 'Back',
    or: 'or',
    appName: 'Nova',
    error: 'Something went wrong',
  },
  nav: {
    home: 'Home',
    dashboard: 'Dashboard',
    admin: 'Admin',
    login: 'Sign in',
    signup: 'Sign up',
    logout: 'Sign out',
    profile: 'Profile',
  },
  home: {
    badge: 'Production-ready starter',
    title: 'Ship multi-language apps fast',
    subtitle:
      'Next.js + Supabase + Vercel starter with auth, RLS, admin, and five locales from day one.',
    ctaPrimary: 'Create account',
    ctaSecondary: 'Sign in',
    feature1Title: 'Server-first',
    feature1Body: 'Server Components and Server Actions — less client JS, faster pages.',
    feature2Title: 'Secure by default',
    feature2Body: 'Supabase Auth + Row Level Security on every table.',
    feature3Title: 'i18n + RTL',
    feature3Body: 'English, Turkish, Russian, Persian, and Hebrew — including right-to-left.',
  },
  auth: {
    loginTitle: 'Welcome back',
    loginSubtitle: 'Sign in to continue',
    signupTitle: 'Create account',
    signupSubtitle: 'Join in under a minute',
    email: 'Email',
    password: 'Password',
    firstName: 'First name',
    lastName: 'Last name',
    forgot: 'Forgot password?',
    noAccount: "Don't have an account?",
    hasAccount: 'Already have an account?',
    submitLogin: 'Sign in',
    submitSignup: 'Create account',
    signupSuccessTitle: 'Check your email',
    signupSuccessBody: 'We sent a confirmation link. Open it to activate your account.',
    forgotTitle: 'Reset password',
    forgotSubtitle: 'We will email you a secure reset link.',
    forgotSubmit: 'Send reset link',
    forgotSent: 'If that email exists, a reset link is on the way.',
    resetTitle: 'Choose a new password',
    resetSubtitle: 'Enter a strong password for your account.',
    resetSubmit: 'Update password',
    newPassword: 'New password',
    confirmPassword: 'Confirm password',
  },
  dashboard: {
    title: 'Dashboard',
    welcome: 'Welcome, {name}',
    pending: 'Your account is pending approval.',
    approved: 'You are approved and ready to go.',
    rejected: 'Your account was not approved. Contact support.',
    noProfile: 'Profile not found yet. Refresh in a moment.',
  },
  admin: {
    title: 'Admin',
    subtitle: 'Manage users and approvals',
    users: 'Users',
    role: 'Role',
    status: 'Status',
    approve: 'Approve',
    reject: 'Reject',
    forbidden: 'You do not have admin access.',
    empty: 'No users yet.',
  },
  language: {
    label: 'Language',
    en: 'English',
    tr: 'Türkçe',
    ru: 'Русский',
    fa: 'فارسی',
    he: 'עברית',
  },
}

export default dict
